### ISSUE TITLE
Setup File error

### ISSUE THREAD

**Issue by anikimmel** [aiml-au/segmesh#1]
Hello!

Whenever I try to run your setup file, I come back with this error: 

![image](https://github.com/aiml-au/segmesh/assets/99368888/028c5dcf-eef3-4b21-84d5-ed7446caa6c4)
 
Any ideas on how to resolve it?

Full stack trace:
running bdist_egg
running egg_info
writing mesh_conv3d.egg-info/PKG-INFO
writing dependency_links to mesh_conv3d.egg-info/dependency_links.txt
writing top-level names to mesh_conv3d.egg-info/top_level.txt
reading manifest file 'mesh_conv3d.egg-info/SOURCES.txt'
writing manifest file 'mesh_conv3d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    setup(
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/segmesh/.conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/segmesh/.conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 436, in build_extensions
    self._check_cuda_version(compiler_name, compiler_version)
  File "/segmesh/.conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 813, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/segmesh/.conda/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 52, in parse
    return Version(version)
  File "/segmesh/.conda/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by anikimmel** [comment]
Actually I fixed this but am getting a series of errors relating to which versions of GCC and G++ and cuda I am using. Is it possible for you to provide a docker file for running the code?

**Comment by deval-shah** [comment]
Hi @anikimmel Thank you for reporting the issue.

Setup Instructions: https://github.com/aiml-au/segmesh?tab=readme-ov-file#1-setup. I was able to complete the setup without any errors in my machine. The machine configuration I used for setup is as follows.

CPU: 13th Gen Intel(R) Core(TM) i9-13900KF
GPU: A6000
Driver Version: 525.147.05   
CUDA Version: 12.0 
Pytorch Version: 2.0.1+cu117

Ideally, the cuda version should match the driver version. If possible, can you please share `nvidia-smi` command output from command line.

1. Would you mind providing screenshots/commands to reproduce this issue?
2. Please share your machine configuration and series of steps that led to other gcc/cuda errors.
